import Head from 'next/head'
import { useEffect, useState } from 'react'

export default function Home() {
  const [jokes , setJokes] = useState(null)

const getJokesRandom = () => {
  fetch('https://candaan-api.vercel.app/api/text/random')
    .then(res => res.json())
    .then(res => {
        setJokes(res.data)
     })
}

useEffect(() => {
  getJokesRandom()
} , [])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <h1>Joks Untuk Anda</h1>
     <button onClick={getJokesRandom}>jokes baru</button>
     <h3>{jokes}</h3> 
    </>
  )
}
